version: '3.4'

networks:
  diabete-net:
    driver: bridge

services:
  patientservice:
    build: ./PatientService
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - diabete-net

  ocelotgateway:
    build:
      context: ./OcelotGateway
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - diabete-net

  microfrontend:
    build: ./MicroFrontend
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      # Dans Docker, pour communiquer avec PatientService et NotesService via HTTPS,
      # utilisez les noms de service et assurez-vous que ces services sont configurés en HTTPS.
      - AccountApi__BaseUrl=https://patientservice:5000/api/
      - NotesApi__BaseUrl=https://notesservice:5003/api/
    networks:
      - diabete-net

  notesservice:
      build:
        context: .
        dockerfile: NotesService/Dockerfile
      ports:
        - "5003:80"
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
      networks:
        - diabete-net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "CnUJ3ge0JAnwUH!A6ZP@r3&ERaW#8z^w"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - diabete-net

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    networks:
      - diabete-net
