networks:
  diabete-net:
    driver: bridge

services:
  patientservice:
    build:
      context: .
      dockerfile: PatientService/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - diabete-net

  ocelotgateway:
    build:
      context: .
      dockerfile: OcelotGateway/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - diabete-net
    depends_on:
      - patientservice
      - notesservice

  microfrontend:
    build:
      context: .
      dockerfile: MicroFrontend/Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - AccountApi__BaseUrl=http://patientservice:80/api/
      - NotesApi__BaseUrl=http://notesservice:80/api/
    networks:
      - diabete-net
    depends_on:
      - patientservice
      - notesservice

  notesservice:
    build:
      context: .
      dockerfile: NotesService/Dockerfile
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - diabete-net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "CnUJ3ge0JAnwUH!A6ZP@r3&ERaW#8z^w"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - diabete-net

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    networks:
      - diabete-net
