version: '3.4'
services:
  patientservice:
    build: ./PatientService
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  ocelotgateway:
    build: ./OcelotGateway
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  microfrontend:
    build: ./MicroFrontend
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "CnUJ3ge0JAnwUH!A6ZP@r3&ERaW#8z^w"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
