services:
  patientservice:
    build: ./PatientService
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./keys:/app/keys

  ocelotgateway:
    build: ./OcelotGateway
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  microfrontend:
    build: ./MicroFrontend
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - AccountApi__BaseUrl=http://patientservice/api/
      - NotesApi__BaseUrl=http://notesservice/api/
    volumes:
      - ./keys:/app/keys
    depends_on:
      - patientservice
      - notesservice

  notesservice:
    build: ./NotesService
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "CnUJ3ge0JAnwUH!A6ZP@r3&ERaW#8z^w"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
